Remove Env Variable Requirement and Add Support for New Secrets in Secret Manager
dsg-polymtl/flockmtl pull request #80
Opened 2024-12-04 01:10 UTC by dorbanianas

This pull request introduces the following changes:

1. **Removal of Environment Variable Requirement**: The necessity to manually set environment variables is removed, simplifying the setup process for users.
   
2. **New Secrets Added to Secret Manager**: The following secrets are now supported in the Secret Manager:
   - `OLLAMA_API_URL`
   - `OPENAI_API_KEY`
   - `AZURE_API_KEY`
   - `AZURE_RESOURCE_NAME`
   - `AZURE_API_VERSION`

2024-12-04 01:34 UTC, queryproc requested changes
We should introduce new secret types: `OPENAI` and `AZURE_OPENAI`.

2024-12-05 20:49 UTC, queryproc approved these changes

2024-12-05 20:49 UTC, queryproc commented on src/model_manager/providers/adapters/ollama.cpp
> +        nlohmann::json completion;
why the tabs?

2024-12-05 20:53 UTC, dorbanianas commented on src/model_manager/providers/adapters/ollama.cpp
> +        nlohmann::json completion;
I'm not sure about it I think the formatter again I will review the full PR and let you know when it's ready

2024-12-06 16:56 UTC, queryproc approved these changes

2024-12-06 17:35 UTC, anasdorbani commented on src/model_manager/providers/adapters/ollama.cpp
> +        nlohmann::json completion;
I think it's not a tab it's spaces that where added because of the for loop as ollama doesn't support batch embedding so we need to embed each value

2024-12-06 19:37 UTC, merged